#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("moneyShow.Resource", IsApplication=true)]

namespace moneyShow
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int notification_action_color_filter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int notification_icon_bg_color = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int notification_material_background_media_default_color = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primary_text_default_material_dark = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int ripple_material_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int secondary_text_default_material_dark = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int secondary_text_default_material_light = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0017
			public const int ResultsTable = 2131427351;
			
			// aapt resource value: 0x7f0b0096
			public const int action0 = 2131427478;
			
			// aapt resource value: 0x7f0b0093
			public const int action_container = 2131427475;
			
			// aapt resource value: 0x7f0b009a
			public const int action_divider = 2131427482;
			
			// aapt resource value: 0x7f0b0094
			public const int action_image = 2131427476;
			
			// aapt resource value: 0x7f0b0095
			public const int action_text = 2131427477;
			
			// aapt resource value: 0x7f0b00a3
			public const int actions = 2131427491;
			
			// aapt resource value: 0x7f0b0005
			public const int async = 2131427333;
			
			// aapt resource value: 0x7f0b0040
			public const int beizhuinput = 2131427392;
			
			// aapt resource value: 0x7f0b0052
			public const int benrishouru = 2131427410;
			
			// aapt resource value: 0x7f0b004e
			public const int benrizhichu = 2131427406;
			
			// aapt resource value: 0x7f0b006e
			public const int benyueshouru = 2131427438;
			
			// aapt resource value: 0x7f0b0053
			public const int benyueyue = 2131427411;
			
			// aapt resource value: 0x7f0b0071
			public const int benyuezhichu = 2131427441;
			
			// aapt resource value: 0x7f0b0015
			public const int benzhoushouru = 2131427349;
			
			// aapt resource value: 0x7f0b0012
			public const int benzhouzhichu = 2131427346;
			
			// aapt resource value: 0x7f0b0006
			public const int blocking = 2131427334;
			
			// aapt resource value: 0x7f0b000b
			public const int button1 = 2131427339;
			
			// aapt resource value: 0x7f0b0073
			public const int button2 = 2131427443;
			
			// aapt resource value: 0x7f0b0097
			public const int cancel_action = 2131427479;
			
			// aapt resource value: 0x7f0b0082
			public const int canyinzhichu = 2131427458;
			
			// aapt resource value: 0x7f0b007a
			public const int checkedTextView1 = 2131427450;
			
			// aapt resource value: 0x7f0b007b
			public const int checkedTextView2 = 2131427451;
			
			// aapt resource value: 0x7f0b007c
			public const int checkedTextView3 = 2131427452;
			
			// aapt resource value: 0x7f0b009e
			public const int chronometer = 2131427486;
			
			// aapt resource value: 0x7f0b0089
			public const int chuxingzhichu = 2131427465;
			
			// aapt resource value: 0x7f0b003f
			public const int costinput = 2131427391;
			
			// aapt resource value: 0x7f0b004c
			public const int datatimeall = 2131427404;
			
			// aapt resource value: 0x7f0b0055
			public const int duoyibi = 2131427413;
			
			// aapt resource value: 0x7f0b007d
			public const int editText1 = 2131427453;
			
			// aapt resource value: 0x7f0b007e
			public const int editText2 = 2131427454;
			
			// aapt resource value: 0x7f0b007f
			public const int editText3 = 2131427455;
			
			// aapt resource value: 0x7f0b00a5
			public const int end_padder = 2131427493;
			
			// aapt resource value: 0x7f0b000c
			public const int fixed1 = 2131427340;
			
			// aapt resource value: 0x7f0b0010
			public const int fixed2 = 2131427344;
			
			// aapt resource value: 0x7f0b0013
			public const int fixed3 = 2131427347;
			
			// aapt resource value: 0x7f0b0016
			public const int fixed4 = 2131427350;
			
			// aapt resource value: 0x7f0b0048
			public const int foodButtond = 2131427400;
			
			// aapt resource value: 0x7f0b0007
			public const int forever = 2131427335;
			
			// aapt resource value: 0x7f0b000a
			public const int gridLayout1 = 2131427338;
			
			// aapt resource value: 0x7f0b0011
			public const int gridLayout2 = 2131427345;
			
			// aapt resource value: 0x7f0b0014
			public const int gridLayout3 = 2131427348;
			
			// aapt resource value: 0x7f0b0086
			public const int gridLayout4 = 2131427462;
			
			// aapt resource value: 0x7f0b008a
			public const int gridLayout5 = 2131427466;
			
			// aapt resource value: 0x7f0b008e
			public const int gridLayout6 = 2131427470;
			
			// aapt resource value: 0x7f0b0078
			public const int gridLayout7 = 2131427448;
			
			// aapt resource value: 0x7f0b004b
			public const int header = 2131427403;
			
			// aapt resource value: 0x7f0b0090
			public const int huafeizhichu = 2131427472;
			
			// aapt resource value: 0x7f0b00a0
			public const int icon = 2131427488;
			
			// aapt resource value: 0x7f0b00a4
			public const int icon_group = 2131427492;
			
			// aapt resource value: 0x7f0b008d
			public const int imageView2 = 2131427469;
			
			// aapt resource value: 0x7f0b0080
			public const int imagecanyin = 2131427456;
			
			// aapt resource value: 0x7f0b0087
			public const int imagechuxing = 2131427463;
			
			// aapt resource value: 0x7f0b008f
			public const int imagehuafei = 2131427471;
			
			// aapt resource value: 0x7f0b0084
			public const int imagelvyou = 2131427460;
			
			// aapt resource value: 0x7f0b0091
			public const int imageshenghuoyongpin = 2131427473;
			
			// aapt resource value: 0x7f0b008b
			public const int imageyiliao = 2131427467;
			
			// aapt resource value: 0x7f0b009f
			public const int info = 2131427487;
			
			// aapt resource value: 0x7f0b0008
			public const int italic = 2131427336;
			
			// aapt resource value: 0x7f0b001f
			public const int jieyu1num = 2131427359;
			
			// aapt resource value: 0x7f0b0025
			public const int jieyu2num = 2131427365;
			
			// aapt resource value: 0x7f0b002b
			public const int jieyu3num = 2131427371;
			
			// aapt resource value: 0x7f0b0031
			public const int jieyu4num = 2131427377;
			
			// aapt resource value: 0x7f0b0037
			public const int jieyu5num = 2131427383;
			
			// aapt resource value: 0x7f0b003d
			public const int jieyu6num = 2131427389;
			
			// aapt resource value: 0x7f0b005e
			public const int jinrishouru = 2131427422;
			
			// aapt resource value: 0x7f0b0061
			public const int jinrizhichu = 2131427425;
			
			// aapt resource value: 0x7f0b0046
			public const int lifeButton = 2131427398;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b000e
			public const int linearLayout1 = 2131427342;
			
			// aapt resource value: 0x7f0b005c
			public const int linearLayout10 = 2131427420;
			
			// aapt resource value: 0x7f0b005f
			public const int linearLayout11 = 2131427423;
			
			// aapt resource value: 0x7f0b0065
			public const int linearLayout12 = 2131427429;
			
			// aapt resource value: 0x7f0b0067
			public const int linearLayout13 = 2131427431;
			
			// aapt resource value: 0x7f0b006c
			public const int linearLayout14 = 2131427436;
			
			// aapt resource value: 0x7f0b006f
			public const int linearLayout15 = 2131427439;
			
			// aapt resource value: 0x7f0b0051
			public const int linearLayout2 = 2131427409;
			
			// aapt resource value: 0x7f0b0054
			public const int linearLayout3 = 2131427412;
			
			// aapt resource value: 0x7f0b0057
			public const int linearLayout4 = 2131427415;
			
			// aapt resource value: 0x7f0b0059
			public const int linearLayout6 = 2131427417;
			
			// aapt resource value: 0x7f0b005b
			public const int linearLayout7 = 2131427419;
			
			// aapt resource value: 0x7f0b0064
			public const int linearLayout8 = 2131427428;
			
			// aapt resource value: 0x7f0b006b
			public const int linearLayout9 = 2131427435;
			
			// aapt resource value: 0x7f0b0056
			public const int listsource = 2131427414;
			
			// aapt resource value: 0x7f0b0085
			public const int lvyouzhichu = 2131427461;
			
			// aapt resource value: 0x7f0b0099
			public const int media_actions = 2131427481;
			
			// aapt resource value: 0x7f0b0009
			public const int normal = 2131427337;
			
			// aapt resource value: 0x7f0b00a2
			public const int notification_background = 2131427490;
			
			// aapt resource value: 0x7f0b009c
			public const int notification_main_column = 2131427484;
			
			// aapt resource value: 0x7f0b009b
			public const int notification_main_column_container = 2131427483;
			
			// aapt resource value: 0x7f0b0047
			public const int outButton = 2131427399;
			
			// aapt resource value: 0x7f0b0042
			public const int radioGroupshouzhi = 2131427394;
			
			// aapt resource value: 0x7f0b0045
			public const int radioGrouptype = 2131427397;
			
			// aapt resource value: 0x7f0b00a1
			public const int right_icon = 2131427489;
			
			// aapt resource value: 0x7f0b009d
			public const int right_side = 2131427485;
			
			// aapt resource value: 0x7f0b000d
			public const int searchView1 = 2131427341;
			
			// aapt resource value: 0x7f0b0092
			public const int shenghuoyongpinzhichu = 2131427474;
			
			// aapt resource value: 0x7f0b003e
			public const int shou = 2131427390;
			
			// aapt resource value: 0x7f0b001a
			public const int shou1num = 2131427354;
			
			// aapt resource value: 0x7f0b0022
			public const int shou2num = 2131427362;
			
			// aapt resource value: 0x7f0b0028
			public const int shou3num = 2131427368;
			
			// aapt resource value: 0x7f0b002e
			public const int shou4num = 2131427374;
			
			// aapt resource value: 0x7f0b0034
			public const int shou5num = 2131427380;
			
			// aapt resource value: 0x7f0b003a
			public const int shou6num = 2131427386;
			
			// aapt resource value: 0x7f0b0043
			public const int shouruButton = 2131427395;
			
			// aapt resource value: 0x7f0b0083
			public const int star = 2131427459;
			
			// aapt resource value: 0x7f0b0098
			public const int status_bar_latest_event_content = 2131427480;
			
			// aapt resource value: 0x7f0b004a
			public const int submit = 2131427402;
			
			// aapt resource value: 0x7f0b0020
			public const int tableRow2 = 2131427360;
			
			// aapt resource value: 0x7f0b0026
			public const int tableRow31 = 2131427366;
			
			// aapt resource value: 0x7f0b0029
			public const int tableRow32 = 2131427369;
			
			// aapt resource value: 0x7f0b0023
			public const int tableRow4 = 2131427363;
			
			// aapt resource value: 0x7f0b002c
			public const int tableRow41 = 2131427372;
			
			// aapt resource value: 0x7f0b002f
			public const int tableRow42 = 2131427375;
			
			// aapt resource value: 0x7f0b0032
			public const int tableRow51 = 2131427378;
			
			// aapt resource value: 0x7f0b0035
			public const int tableRow52 = 2131427381;
			
			// aapt resource value: 0x7f0b0038
			public const int tableRow61 = 2131427384;
			
			// aapt resource value: 0x7f0b003b
			public const int tableRow62 = 2131427387;
			
			// aapt resource value: 0x7f0b0018
			public const int tableRowri1 = 2131427352;
			
			// aapt resource value: 0x7f0b001b
			public const int tableRowri2 = 2131427355;
			
			// aapt resource value: 0x7f0b0002
			public const int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b0074
			public const int textView1 = 2131427444;
			
			// aapt resource value: 0x7f0b0088
			public const int textView10 = 2131427464;
			
			// aapt resource value: 0x7f0b005a
			public const int textView11 = 2131427418;
			
			// aapt resource value: 0x7f0b005d
			public const int textView12 = 2131427421;
			
			// aapt resource value: 0x7f0b0060
			public const int textView13 = 2131427424;
			
			// aapt resource value: 0x7f0b0066
			public const int textView14 = 2131427430;
			
			// aapt resource value: 0x7f0b0068
			public const int textView15 = 2131427432;
			
			// aapt resource value: 0x7f0b006d
			public const int textView16 = 2131427437;
			
			// aapt resource value: 0x7f0b0079
			public const int textView17 = 2131427449;
			
			// aapt resource value: 0x7f0b0070
			public const int textView18 = 2131427440;
			
			// aapt resource value: 0x7f0b0075
			public const int textView2 = 2131427445;
			
			// aapt resource value: 0x7f0b0076
			public const int textView3 = 2131427446;
			
			// aapt resource value: 0x7f0b004d
			public const int textView4 = 2131427405;
			
			// aapt resource value: 0x7f0b004f
			public const int textView5 = 2131427407;
			
			// aapt resource value: 0x7f0b0081
			public const int textView6 = 2131427457;
			
			// aapt resource value: 0x7f0b0050
			public const int textView8 = 2131427408;
			
			// aapt resource value: 0x7f0b001c
			public const int time = 2131427356;
			
			// aapt resource value: 0x7f0b0049
			public const int timeinput = 2131427401;
			
			// aapt resource value: 0x7f0b0004
			public const int title = 2131427332;
			
			// aapt resource value: 0x7f0b0019
			public const int week1 = 2131427353;
			
			// aapt resource value: 0x7f0b0027
			public const int week3 = 2131427367;
			
			// aapt resource value: 0x7f0b002d
			public const int week4 = 2131427373;
			
			// aapt resource value: 0x7f0b0033
			public const int week5 = 2131427379;
			
			// aapt resource value: 0x7f0b0039
			public const int week6 = 2131427385;
			
			// aapt resource value: 0x7f0b0021
			public const int year = 2131427361;
			
			// aapt resource value: 0x7f0b008c
			public const int yiliaozhichu = 2131427468;
			
			// aapt resource value: 0x7f0b001d
			public const int zhi = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int zhi1num = 2131427358;
			
			// aapt resource value: 0x7f0b0024
			public const int zhi2num = 2131427364;
			
			// aapt resource value: 0x7f0b002a
			public const int zhi3num = 2131427370;
			
			// aapt resource value: 0x7f0b0030
			public const int zhi4num = 2131427376;
			
			// aapt resource value: 0x7f0b0036
			public const int zhi5num = 2131427382;
			
			// aapt resource value: 0x7f0b003c
			public const int zhi6num = 2131427388;
			
			// aapt resource value: 0x7f0b0044
			public const int zhichuButton = 2131427396;
			
			// aapt resource value: 0x7f0b000f
			public const int zhoujieyu = 2131427343;
			
			// aapt resource value: 0x7f0b0041
			public const int zhouzhichu = 2131427393;
			
			// aapt resource value: 0x7f0b0077
			public const int zongzhichu = 2131427447;
			
			// aapt resource value: 0x7f0b0058
			public const int 标识图片1 = 2131427416;
			
			// aapt resource value: 0x7f0b0063
			public const int 标识图片2 = 2131427427;
			
			// aapt resource value: 0x7f0b006a
			public const int 标识图片3 = 2131427434;
			
			// aapt resource value: 0x7f0b0062
			public const int 链接图片1 = 2131427426;
			
			// aapt resource value: 0x7f0b0069
			public const int 链接图片2 = 2131427433;
			
			// aapt resource value: 0x7f0b0072
			public const int 链接图片3 = 2131427442;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int dayaccount = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int duoyibi = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int homepage = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int list_view_dataTemplate = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Mainpage = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_action = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_action_tombstone = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_media_action = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_media_cancel_action = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_big_media = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_big_media_custom = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_big_media_narrow = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_big_media_narrow_custom = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_custom_big = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_icon_group = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_lines_media = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_template_media = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_template_media_custom = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int notification_template_part_chronometer = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int notification_template_part_time = 2130968595;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int app_name = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int hello = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int status_bar_notification_info_overflow = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050005
			public const int TextAppearance_Compat_Notification = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int TextAppearance_Compat_Notification_Info = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int TextAppearance_Compat_Notification_Media = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int TextAppearance_Compat_Notification_Time = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int TextAppearance_Compat_Notification_Title = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int Widget_Compat_NotificationActionContainer = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Widget_Compat_NotificationActionText = 2131034122;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
