#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("moneyShow.Resource", IsApplication=true)]

namespace moneyShow
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int ResultsTable = 2131034125;
			
			// aapt resource value: 0x7f050043
			public const int benrishouru = 2131034179;
			
			// aapt resource value: 0x7f05003f
			public const int benrizhichu = 2131034175;
			
			// aapt resource value: 0x7f05005f
			public const int benyueshouru = 2131034207;
			
			// aapt resource value: 0x7f050044
			public const int benyueyue = 2131034180;
			
			// aapt resource value: 0x7f050062
			public const int benyuezhichu = 2131034210;
			
			// aapt resource value: 0x7f05000b
			public const int benzhoushouru = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int benzhouzhichu = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f050072
			public const int canyinzhichu = 2131034226;
			
			// aapt resource value: 0x7f050039
			public const int cateinput = 2131034169;
			
			// aapt resource value: 0x7f050038
			public const int cateshouzhi = 2131034168;
			
			// aapt resource value: 0x7f05006a
			public const int checkedTextView1 = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int checkedTextView2 = 2131034219;
			
			// aapt resource value: 0x7f05006c
			public const int checkedTextView3 = 2131034220;
			
			// aapt resource value: 0x7f050079
			public const int chuxingzhichu = 2131034233;
			
			// aapt resource value: 0x7f050036
			public const int costinput = 2131034166;
			
			// aapt resource value: 0x7f05003c
			public const int datatimeall = 2131034172;
			
			// aapt resource value: 0x7f050046
			public const int duoyibi = 2131034182;
			
			// aapt resource value: 0x7f05006d
			public const int editText1 = 2131034221;
			
			// aapt resource value: 0x7f05006e
			public const int editText2 = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int editText3 = 2131034223;
			
			// aapt resource value: 0x7f050002
			public const int fixed1 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int fixed2 = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int fixed3 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int fixed4 = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int gridLayout2 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int gridLayout3 = 2131034122;
			
			// aapt resource value: 0x7f050076
			public const int gridLayout4 = 2131034230;
			
			// aapt resource value: 0x7f05007a
			public const int gridLayout5 = 2131034234;
			
			// aapt resource value: 0x7f05007e
			public const int gridLayout6 = 2131034238;
			
			// aapt resource value: 0x7f050068
			public const int gridLayout7 = 2131034216;
			
			// aapt resource value: 0x7f05003d
			public const int header = 2131034173;
			
			// aapt resource value: 0x7f050080
			public const int huafeizhichu = 2131034240;
			
			// aapt resource value: 0x7f05007d
			public const int imageView2 = 2131034237;
			
			// aapt resource value: 0x7f050070
			public const int imagecanyin = 2131034224;
			
			// aapt resource value: 0x7f050077
			public const int imagechuxing = 2131034231;
			
			// aapt resource value: 0x7f05007f
			public const int imagehuafei = 2131034239;
			
			// aapt resource value: 0x7f050074
			public const int imagelvyou = 2131034228;
			
			// aapt resource value: 0x7f050081
			public const int imageshenghuoyongpin = 2131034241;
			
			// aapt resource value: 0x7f05007b
			public const int imageyiliao = 2131034235;
			
			// aapt resource value: 0x7f050012
			public const int jieyu = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int jieyu1num = 2131034135;
			
			// aapt resource value: 0x7f05001d
			public const int jieyu2num = 2131034141;
			
			// aapt resource value: 0x7f050023
			public const int jieyu3num = 2131034147;
			
			// aapt resource value: 0x7f050029
			public const int jieyu4num = 2131034153;
			
			// aapt resource value: 0x7f05002f
			public const int jieyu5num = 2131034159;
			
			// aapt resource value: 0x7f050035
			public const int jieyu6num = 2131034165;
			
			// aapt resource value: 0x7f05004f
			public const int jinrishouru = 2131034191;
			
			// aapt resource value: 0x7f050052
			public const int jinrizhichu = 2131034194;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f05004d
			public const int linearLayout10 = 2131034189;
			
			// aapt resource value: 0x7f050050
			public const int linearLayout11 = 2131034192;
			
			// aapt resource value: 0x7f050056
			public const int linearLayout12 = 2131034198;
			
			// aapt resource value: 0x7f050058
			public const int linearLayout13 = 2131034200;
			
			// aapt resource value: 0x7f05005d
			public const int linearLayout14 = 2131034205;
			
			// aapt resource value: 0x7f050060
			public const int linearLayout15 = 2131034208;
			
			// aapt resource value: 0x7f050042
			public const int linearLayout2 = 2131034178;
			
			// aapt resource value: 0x7f050045
			public const int linearLayout3 = 2131034181;
			
			// aapt resource value: 0x7f050048
			public const int linearLayout4 = 2131034184;
			
			// aapt resource value: 0x7f05004a
			public const int linearLayout6 = 2131034186;
			
			// aapt resource value: 0x7f05004c
			public const int linearLayout7 = 2131034188;
			
			// aapt resource value: 0x7f050055
			public const int linearLayout8 = 2131034197;
			
			// aapt resource value: 0x7f05005c
			public const int linearLayout9 = 2131034204;
			
			// aapt resource value: 0x7f050047
			public const int listsource = 2131034183;
			
			// aapt resource value: 0x7f050075
			public const int lvyouzhichu = 2131034229;
			
			// aapt resource value: 0x7f050003
			public const int searchView1 = 2131034115;
			
			// aapt resource value: 0x7f050082
			public const int shenghuoyongpinzhichu = 2131034242;
			
			// aapt resource value: 0x7f050010
			public const int shou = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int shou1num = 2131034129;
			
			// aapt resource value: 0x7f05001a
			public const int shou2num = 2131034138;
			
			// aapt resource value: 0x7f050020
			public const int shou3num = 2131034144;
			
			// aapt resource value: 0x7f050026
			public const int shou4num = 2131034150;
			
			// aapt resource value: 0x7f05002c
			public const int shou5num = 2131034156;
			
			// aapt resource value: 0x7f050032
			public const int shou6num = 2131034162;
			
			// aapt resource value: 0x7f050073
			public const int star = 2131034227;
			
			// aapt resource value: 0x7f05003b
			public const int submit = 2131034171;
			
			// aapt resource value: 0x7f050018
			public const int tableRow2 = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int tableRow31 = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int tableRow32 = 2131034145;
			
			// aapt resource value: 0x7f05001b
			public const int tableRow4 = 2131034139;
			
			// aapt resource value: 0x7f050024
			public const int tableRow41 = 2131034148;
			
			// aapt resource value: 0x7f050027
			public const int tableRow42 = 2131034151;
			
			// aapt resource value: 0x7f05002a
			public const int tableRow51 = 2131034154;
			
			// aapt resource value: 0x7f05002d
			public const int tableRow52 = 2131034157;
			
			// aapt resource value: 0x7f050030
			public const int tableRow61 = 2131034160;
			
			// aapt resource value: 0x7f050033
			public const int tableRow62 = 2131034163;
			
			// aapt resource value: 0x7f05000e
			public const int tableRowri1 = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int tableRowri2 = 2131034131;
			
			// aapt resource value: 0x7f050064
			public const int textView1 = 2131034212;
			
			// aapt resource value: 0x7f050078
			public const int textView10 = 2131034232;
			
			// aapt resource value: 0x7f05004b
			public const int textView11 = 2131034187;
			
			// aapt resource value: 0x7f05004e
			public const int textView12 = 2131034190;
			
			// aapt resource value: 0x7f050051
			public const int textView13 = 2131034193;
			
			// aapt resource value: 0x7f050057
			public const int textView14 = 2131034199;
			
			// aapt resource value: 0x7f050059
			public const int textView15 = 2131034201;
			
			// aapt resource value: 0x7f05005e
			public const int textView16 = 2131034206;
			
			// aapt resource value: 0x7f050069
			public const int textView17 = 2131034217;
			
			// aapt resource value: 0x7f050061
			public const int textView18 = 2131034209;
			
			// aapt resource value: 0x7f050065
			public const int textView2 = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int textView3 = 2131034214;
			
			// aapt resource value: 0x7f05003e
			public const int textView4 = 2131034174;
			
			// aapt resource value: 0x7f050040
			public const int textView5 = 2131034176;
			
			// aapt resource value: 0x7f050071
			public const int textView6 = 2131034225;
			
			// aapt resource value: 0x7f050041
			public const int textView8 = 2131034177;
			
			// aapt resource value: 0x7f05003a
			public const int timeinput = 2131034170;
			
			// aapt resource value: 0x7f05000f
			public const int week1 = 2131034127;
			
			// aapt resource value: 0x7f050019
			public const int week2 = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int week3 = 2131034143;
			
			// aapt resource value: 0x7f050025
			public const int week4 = 2131034149;
			
			// aapt resource value: 0x7f05002b
			public const int week5 = 2131034155;
			
			// aapt resource value: 0x7f050031
			public const int week6 = 2131034161;
			
			// aapt resource value: 0x7f050014
			public const int year = 2131034132;
			
			// aapt resource value: 0x7f05007c
			public const int yiliaozhichu = 2131034236;
			
			// aapt resource value: 0x7f050015
			public const int zhi = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int zhi1num = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int zhi2num = 2131034140;
			
			// aapt resource value: 0x7f050022
			public const int zhi3num = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int zhi4num = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int zhi5num = 2131034158;
			
			// aapt resource value: 0x7f050034
			public const int zhi6num = 2131034164;
			
			// aapt resource value: 0x7f050005
			public const int zhoujieyu = 2131034117;
			
			// aapt resource value: 0x7f050037
			public const int zhouzhichu = 2131034167;
			
			// aapt resource value: 0x7f050067
			public const int zongzhichu = 2131034215;
			
			// aapt resource value: 0x7f050049
			public const int 标识图片1 = 2131034185;
			
			// aapt resource value: 0x7f050054
			public const int 标识图片2 = 2131034196;
			
			// aapt resource value: 0x7f05005b
			public const int 标识图片3 = 2131034203;
			
			// aapt resource value: 0x7f050053
			public const int 链接图片1 = 2131034195;
			
			// aapt resource value: 0x7f05005a
			public const int 链接图片2 = 2131034202;
			
			// aapt resource value: 0x7f050063
			public const int 链接图片3 = 2131034211;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dayaccount = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int duoyibi = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int homepage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_view_dataTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
